### PR TITLE
Follow-up fixes from async refactor

### LINKED ISSUE #575: Chat history is not enabled warning, while chat history is not configured
Since https://github.com/microsoft/sample-app-aoai-chatGPT/pull/460, I receive the message that "Chat history is not enabled", even though I haven't configured this.

This is an optional feature, but it seems this is now enabled out of the box.

image

### PR DESCRIPTION
**Pull request by sarah-widder**
- fix start.cmd
- fix start.sh
- update readme
- fix bug with chat history showing an error when it's not configured
Fixes #575 and #571

### CODE REVIEW

File: start.sh [hunk 1]
```diff
@@ -25,7 +25,7 @@ cd ..
 echo ""
 echo "Starting backend"
 echo ""
-./.venv/bin/python -m flask run --port=5000 --host=127.0.0.1 --reload --debug
+./.venv/bin/python -m quart run --port=50505 --host=127.0.0.1 --reload --debug
```
Comment (iMicknl) [inline start.sh:28]: Error: No such option: --debug :-)

Comment (sarah-widder) [reply start.sh:28]: Shucks! Opened #577
